<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ExploreEase</title>
</head>
<body>
    <header>
        <h1>Welcome to ExploreEase</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Destinations</a></li>
                <li><a href="#">Prices</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <p>Welcome to ExploreEase! We aim to suggest people different destinies and provide information about countries, prices, and the best times to visit.</p>
    </main>
    <footer>
        <p>&copy; 2024 ExploreEase | Created by Maryam Nurmatova</p>
    </footer>
</body>
</html>
